# Example program-specific deployment

FROM cogit-art.orbitlogic.com:5050/aps/store/42 AS base

RUN mkdir -p /42/scenarios/example

COPY program_data/example/scenario/ /42/scenarios/example/
COPY program_data/example/FortyTwoSats.json /

# Note that the scenario directory is specified relative to the 42 installation
ENV FORTYTWO_SCENARIO=scenarios/example
ENV FORTYTWO_GRPC_CONFIG=/FortyTwoSats.json
ENV GRAPHICS_FRONT_END=false

WORKDIR /

ENTRYPOINT [ "/docker-entrypoint.sh" ]
